adminPassword: "alleged pihole beret"

serviceWeb:
  loadBalancerIP: 192.168.1.16
  type: LoadBalancer

serviceDns:
  loadBalancerIP: 192.168.1.15
  annotations:
    metallb.universe.tf/allow-shared-ip: "192.168.1.15"
  type: LoadBalancer

persistentVolumeClaim:
  enabled: true
  storageClass: "longhorn"

# podDnsConfig:
#   enabled: true
#   policy: "None"
#   nameservers:
#   - 1.1.1.1
#   - 1.0.0.1
