adminPassword: "alleged pihole beret"

DNS1: "1.1.1.1" 
DNS2: "1.0.0.1" 

serviceWeb:
  loadBalancerIP: 192.168.1.16
  type: LoadBalancer

serviceDns:
  loadBalancerIP: 192.168.1.15
  annotations:
    metallb.universe.tf/allow-shared-ip: "192.168.1.15"
  type: LoadBalancer

persistentVolumeClaim:
  enabled: true
  storageClass: "longhorn"
